version: 1.2
workflows:
  - subclass: Galaxy
    name: 'NEBNext_Immune_Sequencing'
    primaryDescriptorPath: /nebnext-immune-sequencing/presto_immune_sequencing_v3.20.ga
    authors:
      - orcid: 0000-0001-7390-1094
